version: '3.8'

services:
  task-manager:
    build: ./task-manager  # Points to the Angular app
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - app-network

  api:
    build: ./API  # Points to the Node.js API
    ports:
      - "3000:3000"
    environment:
      - COUCHDB_URL=http://couchdb:5984
    depends_on:
      - couchdb
    networks:
      - app-network

  couchdb:
    image: couchdb:3.2
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=jlpile
      - COUCHDB_PASSWORD=jl0106
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
