services:
  task-manager:
    image: pilejl/task-manager:latest_angular_app  # Use pulled image instead of building
    ports:
      - "8081:80"
    networks:
      - app-network
    restart: always

  api:
    image: pilejl/task-manager:latest_API
    ports:
      - "3000:3000"
    environment:
      - COUCHDB_URL=http://admin:admin@couchdb:5984
    depends_on:
      couchdb:
        condition: service_healthy
    networks:
      - app-network
    restart: always

  couchdb:
    image: pilejl/task-manager:latest_DB
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984"]
      interval: 5s
      retries: 5

networks:
  app-network:
    driver: bridge
