version: '3.8'

services:
  task-manager:
    build: ./task-manager
    ports:
      - "8080:80"
    networks:
      - app-network
    restart: always

  api:
    build: ./API
    ports:
      - "3000:3000"
    environment:
      - COUCHDB_URL=http://admin:admin@couchdb:5984
    depends_on:
      couchdb:
        condition: service_healthy
    networks:
      - app-network
    restart: always

  couchdb:
    image: couchdb:3.2
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984"]
      interval: 5s
      retries: 5

networks:
  app-network:
    driver: bridge
