version: '3.8'  # Use Docker Compose version 3.8

services:
  task-manager:  # Angular app container
    build: ./task-manager  # Path to Angular project
    ports:
      - "8080:80"  # Expose Angular app on localhost:8080
    depends_on:
      - api  # Ensure the API starts before the Angular app
    networks:
      - app-network
    restart: always  # ⚡ Ensures container restarts if it crashes

  api:  # Node.js API container
    build: ./API  # Path to Node.js API project
    ports:
      - "3000:3000"  # Expose API on localhost:3000
    environment:
      - COUCHDB_URL=http://couchdb:5984  # ⚡ Use service name `couchdb` (inside Docker network)
    depends_on:
      - couchdb  # Ensure CouchDB starts before the API
    networks:
      - app-network
    restart: always  # ⚡ Auto-restart if the container stops

  couchdb:  # CouchDB database container
    image: couchdb:3.2  # Use official CouchDB image
    ports:
      - "5984:5984"  # Expose CouchDB on localhost:5984
    environment:
      - COUCHDB_USER=admin  # Set CouchDB admin username
      - COUCHDB_PASSWORD=admin  # Set CouchDB admin password
    networks:
      - app-network
    restart: always  # ⚡ Auto-restart if CouchDB crashes

networks:
  app-network:
    driver: bridge  # Creates a virtual network for all services to communicate
